### ISSUE TITLE
The task is canceled by "pool inactivity"

### ISSUE THREAD

**Issue by christopheblin** [StephenCleary/AspNetBackgroundTasks#3]
Here is the code of my WEB API 2 controller, which is to immediately returning true and then launching an infinite task  :

        [Route("test", Name = "test")]
        [HttpPost]
        public ApiResource<bool> Post()
        {
            BackgroundTaskManager.Run(() =>
            {
                var i = 0;
                while (true)
                {
                    File.AppendAllLines("c:\\mytest.txt", new[] { DateTime.Now.ToString("s") + " " + i++ });
                    Thread.Sleep(TimeSpan.FromSeconds(30));
                    
                }
            });
            return true.AsApi("bool");
        }

The problem I have is that the pool recycling because of inactivity is done event though the task is running :

Here is the relevant windows log where you can see that
1. at 2016-03-14T13:20:40 the pool starts to shutdown because that was 2 minutes no HTTP request was done (which is the time I configured in IIS for testing purposes)
2. at 2016-03-14T13:22:10 the pool is shutdowned ungracefully because the stopping takes to much time

	<?xml version="1.0" encoding="UTF-8"?>
	<Events>
	   <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		  <System>
			 <Provider Name="Microsoft-Windows-WAS" Guid="{524B5D04-133C-4A62-8362-64E8EDB9CE40}" EventSourceName="WAS" />
			 <EventID Qualifiers="32768">5013</EventID>
			 <Version>0</Version>
			 <Level>3</Level>
			 <Task>0</Task>
			 <Opcode>0</Opcode>
			 <Keywords>0x80000000000000</Keywords>
			 <TimeCreated SystemTime="2016-03-14T13:22:10.000000000Z" />
			 <EventRecordID>8592</EventRecordID>
			 <Correlation />
			 <Execution ProcessID="0" ThreadID="0" />
			 <Channel>System</Channel>
			 <Computer>cbn-PC.ACS-INC.FR</Computer>
			 <Security />
		  </System>
		  <EventData>
			 <Data Name="AppPoolID">MCP.GTFS.API</Data>
			 <Data Name="ProcessID">14420</Data>
			 <Binary />
		  </EventData>
		  <RenderingInfo Culture="fr-FR">
			 <Message>L'arrêt d'un processus servant le pool d'applications 'MCP.GTFS.API' a pris trop de temps. L'identificateur de processus était '14420'.</Message>
			 <Level>Avertissement</Level>
			 <Task />
			 <Opcode />
			 <Channel />
			 <Provider>Microsoft-Windows-WAS</Provider>
			 <Keywords>
				<Keyword>Classique</Keyword>
			 </Keywords>
		  </RenderingInfo>
	   </Event>
	   <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		  <System>
			 <Provider Name="Microsoft-Windows-WAS" Guid="{524B5D04-133C-4A62-8362-64E8EDB9CE40}" EventSourceName="WAS" />
			 <EventID Qualifiers="16384">5186</EventID>
			 <Version>0</Version>
			 <Level>4</Level>
			 <Task>0</Task>
			 <Opcode>0</Opcode>
			 <Keywords>0x80000000000000</Keywords>
			 <TimeCreated SystemTime="2016-03-14T13:20:40.000000000Z" />
			 <EventRecordID>8590</EventRecordID>
			 <Correlation />
			 <Execution ProcessID="0" ThreadID="0" />
			 <Channel>System</Channel>
			 <Computer>cbn-PC.ACS-INC.FR</Computer>
			 <Security />
		  </System>
		  <EventData>
			 <Data Name="ProcessID">14420</Data>
			 <Data Name="AppPoolID">MCP.GTFS.API</Data>
			 <Data Name="Minutes">2</Data>
		  </EventData>
		  <RenderingInfo Culture="fr-FR">
			 <Message>Un processus de travail avec l'identificateur de processus '14420' desservant le pool d'applications 'MCP.GTFS.API' a été fermé pour cause d'inactivité. Le délai d'attente du pool d'applications était défini sur 2 minutes. En cas de besoin, un nouveau processus de travail sera démarré.</Message>
			 <Level>Information</Level>
			 <Task />
			 <Opcode />
			 <Channel />
			 <Provider>Microsoft-Windows-WAS</Provider>
			 <Keywords>
				<Keyword>Classique</Keyword>
			 </Keywords>
		  </RenderingInfo>
	   </Event>
	</Events>

In the text file created in the infinite loop, I can see that the last activity is at 2016-03-14T13:21:47.

My question is : why IIS is not seeing my Background thread as an activity ? How can I debug that (i.e how can I find why IIS is not thinking my thread is an activity) ?

**Comment by StephenCleary** [comment]
"Activity" in IIS means processing HTTP requests. There isn't a way to keep IIS alive from within the process; it has to be external. Most hosting providers (e.g., Azure) provide a simple automatic "ping" that will keep your app alive, if you opt into that functionality.
