### ISSUE TITLE
Facing problem while trying to unit test the code.

### ISSUE THREAD

**Issue by San252** [StephenCleary/AspNetBackgroundTasks#5]
Hi Stephen,

I am using your library for background tasks, I found it very useful, Thank you for the good code.
But I have few issues while unit testing the code put in background task.
Since we don't have control over when the task is created or exeuted, not able to unit test the code.
For that reason, I made few changes to the library code, in which I used "Task.Factory.StartNew()" instead Task.Run().
The code in "RegisterdTasks" looks as follows,

```
 public void Run(Func<Task> operation, TaskScheduler taskScheduler)
 {
       Register(Task.Factory.StartNew(operation, CancellationToken.None, TaskCreationOptions.None, taskScheduler), taskScheduler);
 }
 
private void Register(Task task, TaskScheduler taskScheduler)
{
     _count.AddCount();

            task.ContinueWith(
                _ => _count.Signal(),
                CancellationToken.None,
                TaskContinuationOptions.ExecuteSynchronously,
                taskScheduler);       
}        
```

The taskScheduler is "TaskScheduler.Default" in normal execution time, but I am passing customized taskScheduler when unit testing, so that I can force the tasks to execute.

I referred 3rd approach mentioned in link "https://msdn.microsoft.com/en-us/magazine/dn818494.aspx" for unit testing purpose.
And I am using MSTest as framework for unit tetsing(and I cannot replace it with any other framework for now).

So my doubts are:

1) Is the library feasible for  "Task.Factory.StartNew()" instead Task.Run()?
2) If yes, will "Task.Factory.StartNew()" be registered in ASP.Net runtime ?

Thanks in advance.

**Comment by StephenCleary** [comment]
No, this code will not work correctly for asynchronous tasks. This is because `StartNew` doesn't understand asynchronous delegates (`Func<Task>`). You could possibly get it working by adding a call to `Unwrap`.

If you need to unit test your background tasks, I'd recommend injecting an `IBackgroundTasks` service, which gives you full control over how to run those tasks.

**Comment by San252** [comment]
Thank you for the suggestion. I will try that out +1
