### ISSUE TITLE
dotnet core compatible

### ISSUE THREAD

**Issue by A-Programmer** [StephenCleary/AspNetBackgroundTasks#6]
Does this package work in dotnet core 2?

**Comment by StephenCleary** [comment]
No. Do you need ASP.NET Core support? (You can do it yourself with some more code [as such](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice))

**Comment by A-Programmer** [comment]
I was just asking, your package is easy to use and I planed to use if I need in future. Thanks

**Comment by StephenCleary** [comment]
In that case, I'm going to close this until someone really needs this library on ASP.NET Core.
